title: Bloody Blogs
email: thorn@bloodythorn.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my blog where I discuss video games, programing and other interests.
baseurl: ''
url: 'https://www.bloodythorn.com'
github_username:  bloodythorn

google_analytics: UA-154424587-1

header_pages:
  - index.md
  - about.md

footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

#style: light # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - '*.sublime-*'
